name: Build & Deploy Spring app

on:
  workflow_dispatch  
#  push:
#    branches:
#      - main

jobs:
  build-deploy:
    name: Build and Deploy Springboot for beginners
    runs-on: ubuntu-latest
    steps:
      - name:  Checkout code
        uses:  actions/checkout@v4

      - name:  Get the current Date
        id:  date
        run: echo "::set-output name=date::$(date +%Y-%m-%d)"
                
      - name:  Setup JDK 17
        uses:  actions/setup-java@v4
        with:  
          distribution:  'temurin'
          java-version:  21

      - name:  Unit Tests
        run:  mvn -B test  --file pom.xml
    
      - name:  Build the application
        run:  |
          mvn clean
          mvn -B package --file pom.xml

# Creating the docker image from application,
# A container with jar file of application and 
# publish on docker hub (push image)
      - name:  Build docker Image
        uses:  docker/build-push-action@v5
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/github-images':'${{steps.date.outputs.date }}
    
      - name:  Log in to docker
        uses:  docker/login-action@v3
        with:
          username:  ${{ secrets.DOCKER_HUB_USERNAME}}
          PASSWORD:  ${{ secrets.DOCKER_HUB_ACCESS_TOKEN}}
      
      - name: Push Image to dockerhub
        uses: docker/build-push-action@v5
        with:
          context:  .
          dockerfile:  Dockerfile
          push:  true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/github-images':'${{steps.date.outputs.date }}




